service: images

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-users

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  environment:
    tableName: ${self:custom.tableName}
  deploymentBucket:
    name: ggarsa-${self:provider.stage}-deploy
    serverSideEncryption: AES256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ UsersTable, Arn ]

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

functions:
  create:
    handler: create.main
    events:
      - http:
          path: images
          method: post
          cors: true
          authorizer: aws_iam
    layers:
      - ${self:custom.layers.${self:provider.stage}.libs}
  get-all:
    handler: list.main
    events:
      - http:
          path: images
          method: get
          cors: true
          authorizer: aws_iam
    layers:
      - ${self:custom.layers.${self:provider.stage}.libs}

resources:
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}