#
# Layer: module-libs
#
service: helpers-nodex

custom:
  bucket: ggarsa-${self:provider.stage}-deploy

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

layers:
  helpers:
    path: './nodejs'
    name: ${self:service}-${self:provider.stage}
    description: helpers layer
    compatibleRuntimes:
      - nodejs10.x
    retain: false
resources:
  Outputs:
    HelpersLayerExport:
        Value:
          Ref: HelpersLambdaLayer
        Export:
          Name: HelpersLambdaLayer